### ISSUE TITLE
I init a xrp node, but i cannot use Ripple Data API v2

### ISSUE THREAD

**Issue by spursy** [ripple/rippled#2651]
After I init a xrp node, but i cannot use data api. I have the followed issues:

```
error stack is StatusCodeError: 400 - "Unable to parse request: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n\r\n"
    at new StatusCodeError (D:\mywork-git\nodejobs\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\mywork-git\nodejobs\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\mywork-git\nodejobs\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\mywork-git\nodejobs\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (D:\mywork-git\nodejobs\node_modules\request\request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (D:\mywork-git\nodejobs\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by nbougalis** [comment]
The Data API v2 is not part of `rippled`.

**Comment by yuexk** [comment]
how to use the Data PAI v2?
