### ISSUE TITLE
secp256k1 changes the public key outside of the intended scope

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2720]
The `unsigned char pubkey[33];` gets created and then checked in this function:
https://github.com/ripple/rippled/blob/63c3fc30d84d4ab4fa4510172470b336e7a5a89b/src/ripple/protocol/impl/SecretKey.cpp#L242-L250

It then gets explicitly set to all null-bytes in `memset(output, 0, len);`, when the key is being serialized:

https://github.com/ripple/rippled/blob/63c3fc30d84d4ab4fa4510172470b336e7a5a89b/src/secp256k1/src/secp256k1.c#L165-L186

Address Sanitizer logs this as an error, since this happens outside of the scope of `derivePublicKey` as far as I understand it.

It doesn't look security critical to me (more like ASAN not understanding that this memory write is intended), thus the public bug report.

Here's the full output of ASAN (from https://travis-ci.org/MarkusTeufelberger/rippled-distrotest/jobs/441236590):
```=================================================================
==4693==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7fff8a51ca00 at pc 0x7fce206778d1 bp 0x7fff8a51c760 sp 0x7fff8a51bf08
WRITE of size 33 at 0x7fff8a51ca00 thread T0 (rippled: main)
ripple.app.Manifest apply
    #0 0x7fce206778d0 in __interceptor_memset /build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:709
    #1 0x556776dd30c7 in secp256k1_ec_pubkey_serialize ../../../src/secp256k1/src/secp256k1.c:176
    #2 0x55677685f445 in ripple::derivePublicKey(ripple::KeyType, ripple::SecretKey const&) ../../../src/ripple/protocol/impl/SecretKey.cpp:244
    #3 0x55677685fccb in ripple::randomKeyPair(ripple::KeyType) ../../../src/ripple/protocol/impl/SecretKey.cpp:289
    #4 0x556774b0bc53 in ripple::test::Manifest_test::run() ../../../src/test/app/Manifest_test.cpp:674
    #5 0x556774d29e93 in void beast::unit_test::suite::run<void>(beast::unit_test::runner&) ../../../src/beast/extras/beast/unit_test/suite.hpp:589
    #6 0x556774d1081d in void beast::unit_test::suite::operator()<void>(beast::unit_test::runner&) ../../../src/beast/extras/beast/unit_test/suite.hpp:428
    #7 0x556774cfe621 in beast::unit_test::make_suite_info<ripple::test::Manifest_test>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int)::{lambda(beast::unit_test::runner&)#1}::operator()(beast::unit_test::runner&) const ../../../src/beast/extras/beast/unit_test/suite_info.hpp:120
    #8 0x556774d34f2c in std::_Function_handler<void (beast::unit_test::runner&), beast::unit_test::make_suite_info<ripple::test::Manifest_test>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int)::{lambda(beast::unit_test::runner&)#1}>::_M_invoke(std::_Any_data const&, beast::unit_test::runner&) /usr/include/c++/8.2.1/bits/std_function.h:297
    #9 0x5567735117ea in std::function<void (beast::unit_test::runner&)>::operator()(beast::unit_test::runner&) const /usr/include/c++/8.2.1/bits/std_function.h:687
    #10 0x556773509cb6 in beast::unit_test::suite_info::run(beast::unit_test::runner&) const ../../../src/beast/extras/beast/unit_test/suite_info.hpp:86
    #11 0x55677351d38c in bool beast::unit_test::runner::run<void>(beast::unit_test::suite_info const&) ../../../src/beast/extras/beast/unit_test/runner.hpp:186
    #12 0x556773514feb in bool ripple::test::multi_runner_child::run_multi<ripple::multi_selector>(ripple::multi_selector) ../../../src/test/unit_test/multi_runner.h:304
    #13 0x5567734f8f9c in runUnitTests ../../../src/ripple/app/main/Main.cpp:240
    #14 0x5567734fc4ad in ripple::run(int, char**) ../../../src/ripple/app/main/Main.cpp:462
    #15 0x556773502e14 in main ../../../src/ripple/app/main/Main.cpp:815
    #16 0x7fce1f606222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)
    #17 0x55677314f2ad in _start (/rippled/build/cmake/gcc.debug/rippled+0x5a4b2ad)
Address 0x7fff8a51ca00 is located in stack of thread T0 (rippled: main) at offset 448 in frame
    #0 0x55677685f231 in ripple::derivePublicKey(ripple::KeyType, ripple::SecretKey const&) ../../../src/ripple/protocol/impl/SecretKey.cpp:229
  This frame has 8 object(s):
    [32, 33) '<unknown>'
    [96, 104) 'len'
    [160, 176) '<unknown>'
    [224, 240) '<unknown>'
    [288, 320) '<unknown>'
    [352, 416) 'pubkey_imp'
    [448, 481) 'pubkey' <== Memory access at offset 448 is inside this variable
    [544, 577) 'buf'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope /build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:709 in __interceptor_memset
Shadow bytes around the buggy address:
  0x10007149b8f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007149b900: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 01 f2 f2 f2
  0x10007149b910: f2 f2 f2 f2 00 f2 f2 f2 f2 f2 f2 f2 00 00 f2 f2
  0x10007149b920: f2 f2 f2 f2 00 00 f2 f2 f2 f2 f2 f2 00 00 00 00
  0x10007149b930: f2 f2 f2 f2 00 00 00 00 00 00 00 00 f2 f2 f2 f2
=>0x10007149b940:[f8]f8 00 00 01 f2 f2 f2 f2 f2 f2 f2 00 00 00 00
  0x10007149b950: 01 f2 f2 f2 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007149b960: 00 00 f1 f1 f1 f1 00 00 00 00 f2 f2 f2 f2 00 00
  0x10007149b970: 00 00 00 00 f2 f2 00 00 00 00 00 00 00 00 00 00
  0x10007149b980: 00 00 00 00 f1 f1 f1 f1 f8 f2 f2 f2 f2 f2 f2 f2
  0x10007149b990: 01 f2 f2 f2 f2 f2 f2 f2 01 f2 f2 f2 f2 f2 f2 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==4693==ABORTING```

**Comment by nbougalis** [comment]
I appreciate this report. After looking at the code, I believe that this is a false positive. I will close this, but if anyone suspects this is a problem, please do reopen it.
